//
// Created by leand on 16.01.2024.
//

#ifndef SOCKETTEST_MOVEMENTDIRECTION_H
#define SOCKETTEST_MOVEMENTDIRECTION_H

enum class MovementDirection
{
    MOVE_FORWARD,
    MOVE_BACK,
    MOVE_LEFT,
    MOVE_RIGHT,
    MOVE_EMERGENCY_STOP,
    MOVE_STOP,
};

#endif //SOCKETTEST_MOVEMENTDIRECTION_H
