//
// Created by sheik on 12/15/2023.
//

#ifndef CODE_GLOBAL_VARIABLE_H
#define CODE_GLOBAL_VARIABLE_H

#define MAX_SEARCH_TIME 1000
#define MAX_LEADER_RANGE 10000

#define MAX_NEARBY_TRUCK 5

#endif //CODE_GLOBAL_VARIABLE_H
